receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      load:
      network:
      filesystem:
      

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"  # Port for Prometheus to scrape metrics

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus]
