apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: MongoDB
    type: mongodb
    access: proxy
    url: mongodb://mongodb:27017
